### ISSUE TITLE
Need a way to set Proxy in Transporter

### ISSUE THREAD

**Issue by SwampDragons** [masterzen/winrm#106]
Hi, I maintain [Packer](https://github.com/hashicorp/packer) and we use your library for our winrm communications. We recently discovered that we cannot set the NO_PROXY environment variable during our build and have it picked up by your transporter, because the way ProxyFromEnvironment works here, https://github.com/masterzen/winrm/blob/master/http.go#L57, it's instantiated the very first time Packer makes a request using the net/http library, which is before we know the IP address of the instance we want to add to NO_PROXY.  

I can probably copy the majority of the http.go file and tweak it from within Packer and feed it in via decorators, but it would cause many fewer headaches if we could add a proxy function directly to clientRequest, the way you currently handle the "Dial" option. 

I have a working diff [here](https://github.com/SwampDragons/winrm/commit/56783be1f9bb807c1a6937eea01c6a90f7a4e6a8) and I'm happy to open a PR if it's something you're willing to add.

**Comment by masterzen** [comment]
Hi @SwampDragons ,

I understand your issue. 
Please send me a PR, I'll merge it ASAP.

Thanks !

**Comment by SwampDragons** [comment]
Great, I'll do that now.
