### ISSUE TITLE
function ends without a return statement

### ISSUE THREAD

**Issue by hach-que** [masterzen/winrm#11]
Seeing this build error on go 1.0.3:

```
/usr/lib64/go/src/pkg/github.com/masterzen/winrm/winrm/http.go:15: function ends without a return statement
```

I added 'return' to the end of the function (outside the if / else) and it then built successfully.

**Comment by zl4bv** [comment]
FYI, saw this issue with go 1.0.2. Not seeing this issue with go 1.4.2.
