### ISSUE TITLE
Encrypted NTLM Connection

### ISSUE THREAD

**Issue by mertcelen** [masterzen/winrm#110]
I was wondering if it's possible to provide encrypted ntlm request via 5985. I know the fact that it's not ideal but many Windows applications use it that way because it's always enabled like this in servers by default and it's dead simple to enable it clients via GPO.

Microsoft have this post about how dangerous it is without encryption.

https://devblogs.microsoft.com/powershell/compromising-yourself-with-winrms-allowunencrypted-true/

**Comment by masterzen** [comment]
I believe it's possible, see the 3rd code example in the [README](https://github.com/masterzen/winrm#library-usage).
I think it would be safer to use HTTPS anyway (so port 5986), I think it might be possible to run the Winrm https listener on port 5985 (if you can configure all clients to speak https on this port).

**Comment by mertcelen** [comment]
HTTPS is definetly ok, but do we still need to disable encryption with ssl? If so, that's still bad because we cannot force all the computers to disable encryption.

About example, that's actually what I'm working on atm. NTLM is working well but encryption is the only problem left.

**Comment by masterzen** [comment]
I'm afraid I don't know enough about NTLMSSP/CredSSP to answer your question. I suggest that you try using the NTLM transport in combination with encryption and report if it works or not.
It was my understanding that this requires kerberos, and I'm afraid [Go-ntlmssp](https://github.com/Azure/go-ntlmssp) doesn't support encryption as defined in the [full NTML protocol documentation](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-nlmp/26c42637-9549-46ae-be2e-90f6f1360193))

**Comment by mertcelen** [comment]
Hi again!
I've finally managed to get it working. For some weird reason,  ntlm works with encryption through ssl. I don't mean tls encryption, ntlm's encryption so we don't need to disable any security details. To get it fully working, use ansible's winrm setup script  [here](https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1)

PS:You can also run this script via GPO's and supply certificate for much more better security.

I'm actually closing the issue, thanks for tip :) I kindly suggest you to put some information about security so people wouldn't use insecure connection.
