### ISSUE TITLE
Plans to support Domain Users?

### ISSUE THREAD

**Issue by ryno75** [masterzen/winrm#115]
From the `README.md`...
```
Note: this library doesn't support domain users (it doesn't support GSSAPI nor Kerberos). It's primary target is to execute remote commands on EC2 windows machines.
```

Are there any plans to add support for domain users?

**Comment by brettjacobson** [comment]
This would be very valuable for Enterprises with Windows domains.

**Comment by masterzen** [comment]
I do understand that it would be very useful. 
Unfortunately I don't know how to do that, and I don't have the corporate environment that would allow me to even test this feature.
I would of course welcome any contributions that go in this direction.
A possible solution would be to use https://github.com/jcmturner/gokrb5 and create a new transport for this library.

**Comment by taliesins** [comment]
Perhaps we can close this now that #123 has been implemented?

**Comment by masterzen** [comment]
Feature has been implemented, closing
