### ISSUE TITLE
winrm process hangs

### ISSUE THREAD

**Issue by hach-que** [masterzen/winrm#12]
I've encountered an issue where winrm hangs while waiting for processes to complete on a t1.micro, but the processes are no longer running on the remote host.  The `winrshost.exe` processes are still around (in this case I'm running git clone).

This was encountered when running `git clone` 4 times in 4 different directories (in parallel).

**Comment by mwhooker** [comment]
I've also noticed that winrm doesn't seem to detect when the remote end disconnects. If I run sysprep /shutdown my winrm client hangs forever.

**Comment by roblabla** [comment]
Why was this closed? It's still an issue as far as I can tell, and hashicorp packer is still blocked on this issue to avoid having hangs in its provisioning system (See the linked issue).
