### ISSUE TITLE
User profile is not loaded before running command

### ISSUE THREAD

**Issue by hach-que** [masterzen/winrm#13]
The user profile is not loaded on the remote host before running the command.  This means that the encryption keys used by, e.g. NuGet, are not accessible.

See http://blog.stangroome.com/2012/05/17/powershell-remoting-user-profiles-delegation-and-dpapi/ for more information.  I'm guessing there's some way of telling WinRM to do this as `Enter-PSSession` in PowerShell does it, but not `Invoke-Command`.

**Comment by pecigonzalo** [comment]
I know this is really old, but i can try and give this a look. I think its just a matter of changing a parameter on the SOAP message.

**Comment by masterzen** [comment]
@pecigonzalo go ahead and submit a PR, I'll merge it.

**Comment by hoenirvili** [comment]
@masterzen close?

**Comment by iaitov** [comment]
hello, is there some workaround for this situation, I had the same problem with Invoke-Command and DPAPI

**Comment by posilva** [comment]
Hello, @pecigonzalo what parameter needs to be changed in the SOAP message, I would be happy to contribute with a PR.

If you could share some docs or links I would take a look. I am facing the same issue reported in this ticket.

**Comment by BLZB0B** [comment]
9 years after the original issue creation - this is still causing issues - does anyone know a work around or what the "proper" fix should be ?

**Comment by masterzen** [comment]
I'm really not knowledgeable enough with PS to be able to implement/test this myself. But I would be happy to review/merge any fix.
