### ISSUE TITLE
Extract soap package

### ISSUE THREAD

**Issue by GeertJohan** [masterzen/winrm#16]
I think the soap package is useful on its own. Any plans to extract it to a separate repository?

**Comment by masterzen** [comment]
The soap implementation here is very far from a usable soap underlying system (for instance it supports only creating soap messages, no general parsing), and is very tailored toward winrm.
So I'm not sure it would be very useful for anyone beside the winrm library :(

**Comment by GeertJohan** [comment]
Oh, I think it provides the most features of all soap packages currently available and hoped it would be developed further to provide a full soap implementation. No plans for that?

**Comment by hoenirvili** [comment]
@masterzen close?

**Comment by masterzen** [comment]
Closing since I won't have time to work on such feature. If anyone want to take care of this, please reopen.
