### ISSUE TITLE
winrm command does not propagate exit code

### ISSUE THREAD

**Issue by robdaemon** [masterzen/winrm#17]
When you run the winrm command line tool, it does not propagate the exit code from the command, so it is difficult to use the tool in a script.

**Comment by masterzen** [comment]
Hi @robdaemon 

Thanks for the bug and PR. This was removed in commit cfef3a610d1a3b4516d66c76f12832d9d8d534db ported by @mefellows from @sneal code for the Packer winrm communicator.

@sneal, @mefellows would it be possible to have the exit code back?
I never quite understood why we removed it in the first place, but I suppose we had a good reason, isn't it?
What would be the implication for the projects that depends on winrm?

**Comment by mefellows** [comment]
I think it's a good idea to have it return a valid exit code, I can't recall the exact reasons for its removal but it was part of a 'working' code base that @sneal had put together so at the time I thought best to keep it in. Let's wait for his view, but if there isn't a strong reason lets get it in now.

As for Packer and related systems, we can take the hit now whilst we are still 'alpha' - I'm happy to work in the changes they shouldn't be anything too onerous.

**Comment by masterzen** [comment]
@mefellows, ok, that sounds like a good plan.

Thanks!

**Comment by sneal** [comment]
Who removed the exit code, that was dumb :smile:

**Comment by masterzen** [comment]
OK, so everybody agrees on having the exitCode back again? :)

**Comment by mefellows** [comment]
Agreed. I'll checkout the PR locally and make the changes. I won't be able
to get onto this until next week (likely) but feel free to update the WinRM
library first and we can go from there.

On Fri, Feb 27, 2015 at 2:05 AM, Brice Figureau <notifications@github.com>
wrote:

> OK, so everybody agrees on having the exitCode back again? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/masterzen/winrm/issues/17#issuecomment-76193255>.
>



-- 
Matt Fellows
- http://www.onegeek.com.au/
