### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by robdaemon** [masterzen/winrm#19]
It would be great to have full HTTPS support for WinRM, including specifying a CA certificate, the ability to skip validation (which I don't recommend, but some actually use), etc.

**Comment by robdaemon** [comment]
I have a PR I'm ready to submit that adds a -https flag, a -insecure flag and a -cacert flag. It does slightly change the NewClient/NewClientWithParameters so that it can return an error if the CA cert cannot be loaded though.

I'm not so sure that the -https flag is the right way to go - I contemplated replacing -host and -port with -url instead.

**Comment by masterzen** [comment]
Hi,

I had https support in mind for a long time, but never had the time to really implement it.

Please publish the PR so that we can discuss the design/code and how it breaks the API (or not).

Thanks!

**Comment by robdaemon** [comment]
Okay, submitted the PR. Looking forward to feedback! It's not a big change.
