### ISSUE TITLE
Separating the cli executable from the library.

### ISSUE THREAD

**Issue by hoenirvili** [masterzen/winrm#49]
@masterzen think it's a good time to make this proposal
I propose to decouple the executable code from the api code. It's starts to be ugly and we should use a library-framework to easily customize and develop our binary-executable-tool.
This way it's more easily to make changes to the API without adding/deleting things on executable and vice-versa. Plus a better error handling system in the code overal. What do you think?

We could easily use this wonderful libraries for command line apps.
https://github.com/spf13/cobra
https://github.com/codegangsta/cli
https://github.com/hoenirvili/Skapt
https://github.com/alecthomas/kingpin

**Comment by masterzen** [comment]
@hoenirvili 
I think we should do the separation. I'm going to see how I can do it this week.
What I'd also like to do is add more logging to the library so that we can run it in debug mode to help troubleshooting.

Any idea of a logging library we could use that could fit all our use cases (like Packer or direct usage of winrm).

**Comment by hoenirvili** [comment]
@masterzen 
I think these two should do the trick:
https://github.com/Sirupsen/logrus
https://github.com/tj/go-debug (very light weight)

**Comment by hoenirvili** [comment]
@masterzen so what do you think?

**Comment by masterzen** [comment]
@hoenirvili I think I don't want to introduce a dependency for the library (I'm OK to do that for the cli part when we'll split it). I first want to address #48 before addressing this.

Regarding the logging, I think the library part should have its own `Logger` interface (doing nothing by default or using default golang `log`), which a client (using the library) could provide by implementing the interface on top of its own logging library or code.

Something akin to:
~~~go
type Logger interface {
	Debug(msg string)
	Info(msg string)
	Warn(msg string)
	Error(msg string)
}
~~~ 

This is not yet very clear in my mind how to make it work in Go :)

**Comment by masterzen** [comment]
Reopening, bad push marked it fixed.
