### ISSUE TITLE
Fail to connect to Azure Vm

### ISSUE THREAD

**Issue by vladimir-shcherbakov** [masterzen/winrm#5]
Hi,

I'm looking for a working golang WinRm implementation for Azure VMs. 

So in my case I can execute remote commands with PowerShell:

![image](https://cloud.githubusercontent.com/assets/6579928/4049561/9ae6c688-2d4e-11e4-9943-db6a8257d751.png)

But with your winrm package - connection fails:

![image](https://cloud.githubusercontent.com/assets/6579928/4049628/4c177c86-2d4f-11e4-9e00-5ed186d67d9c.png)

![image](https://cloud.githubusercontent.com/assets/6579928/4049666/aad71a42-2d4f-11e4-9077-e96765e1130e.png)

What did I miss?

Thanks!

**Comment by paulmey** [comment]
This is now fixed. I can connect to Azure machines using NTLM/Negotiate

**Comment by selvik** [comment]
@paulmey Thanks for the updating this thread! I am looking for a way to authenticate in to an Azure VM. Would you happen to have pointers/code snippet on how to use the NTLM/negotiate method?

**Comment by selvik** [comment]
@paulmey I figured it out. Thanks for your update here that lead me to it! 

The code snippet in the top-level readme.md of this project was all that was needed! 

Pasting it here for anyone who comes by this issue:
`params := winrm.DefaultParameters()`
`params.TransportDecorator = func(t *http.Transport) http.RoundTripper { return ntlmssp.Negotiator{t} }`
`client, err := winrm.NewClientWithParameters(..., params)`

**Comment by paulmey** [comment]
@selvik Awesome. Let me know if you run into any issues. The ntlmssp project could use some feedback.

**Comment by masterzen** [comment]
Closing since this is now fixed.
