### ISSUE TITLE
winrm building error (empty Private Key)

### ISSUE THREAD

**Issue by OCram85** [masterzen/winrm#53]
I got the following error while building winrm. Any ideas what I did wrong?
I`ve already done:
- `export $GOPATH=/tmp/gotmp`
- installed GO with: `apt-get install golang*`
- exported `http_proxy` and https_proxy for downloading the src.
- OS: Linux Mint 17.3

Detailed Error Message
-------------------------------
```
mintlab/winrm # make
==> Installing dependencies
==> Building
# github.com/masterzen/winrm/winrm
/tmp/gotmp/src/github.com/masterzen/winrm/winrm/certgen.go:191: t.Public undefined (type *rsa.PrivateKey has no field or method Public)
/tmp/gotmp/src/github.com/masterzen/winrm/winrm/certgen.go:193: t.Public undefined (type *ecdsa.PrivateKey has no field or method Public)
make: *** [all] Error 2
```

**Comment by hoenirvili** [comment]
@masterzen decoupled in this pull request #49. Also the generation for x509 certs will be in the winrm command line tool (other pkg).

**Comment by hoenirvili** [comment]
Now we are refactoring alot of code and I don't think you should use the HEAD for now.

**Comment by OCram85** [comment]
Thanks for your quick response!
So which branch or commit should I choose?

**Comment by masterzen** [comment]
The certgen code is not yet merged, master is still stable.

This is probably a go version issue. Make sure you have at least go 1.5.

**Comment by masterzen** [comment]
@OCram85 you can use something like https://github.com/travis-ci/gimme to get a newer version of Go than what your distribution offers you.

**Comment by OCram85** [comment]
alright, I was using:
`go version go1.2.1 linux/amd64`

I updated to `go version go1.6.2 linux/amd64` and now it works!

**Comment by OCram85** [comment]
Now I hope I get this done https://secure.phabricator.com/w/community_resources/configuring_a_windows_build_agent_for_drydock/

:+1:

**Comment by masterzen** [comment]
Marking as closed, good luck @OCram85 :)
