### ISSUE TITLE
http error 500 still occurring

### ISSUE THREAD

**Issue by hach-que** [masterzen/winrm#54]
We're still getting errors like these on master:

```
http error: 500 - <s:Envelope xml:lang="en-US" xmlns:s="http://www.w3.org/2003/05/soap-envelope" 
xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing" 
xmlns:x="http://schemas.xmlsoap.org/ws/2004/09/transfer" 
xmlns:e="http://schemas.xmlsoap.org/ws/2004/08/eventing" 
xmlns:n="http://schemas.xmlsoap.org/ws/2004/09/enumeration" 
xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd" 
xmlns:p="http://schemas.microsoft.com/wbem/wsman/1/wsman.xsd"><s:Header>
<a:Action>http://schemas.dmtf.org/wbem/wsman/1/wsman/fault</a:Action>
<a:MessageID>uuid:79C09BE6-E600-4E70-BD9F-38988C626813</a:MessageID>
<a:To>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:To>
<a:RelatesTo>uuid:62361711-a467-4cb3-4da1-5e772061509b</a:RelatesTo></s:Header><s:Body>
<s:Fault><s:Code><s:Value>s:Receiver</s:Value><s:Subcode><s:Value>w:TimedOut</s:Value>
</s:Subcode></s:Code><s:Reason><s:Text xml:lang="en-US">The WS-Management service cannot 
complete the operation within the time specified in OperationTimeo
```

The system we're running WinRM through cuts off after a certain number of bytes in the log, so that's all the information we have.

On master, we see less http error 500s, but occasionally we're still seeing these (especially today it's much much higher).

**Comment by masterzen** [comment]
Hi @hach-que ,

Thanks for the report. The recover code is looking for `OperationTimeout` which appears truncated in your output. This might explain why it doesn't detect correctly the Operation timeout.

Beside fixing the problem by correctly implementing the operation timeout (parsing the SOAP response and getting the fault code), can you try the following workaround and let me know if that fixes the issue:

* change line: https://github.com/masterzen/winrm/blob/master/command.go#L134 by this one:
~~~go
if strings.Contains(err.Error(), "w:TimedOut") {
~~~ 

Optionally you might want to change the https://github.com/masterzen/winrm/blob/master/parameters.go#L18 default timeout parameter to something larger than 60s (for instance `PT300S` for a 5 minutes timeout).

Please let me know how it goes,
Thanks

**Comment by hach-que** [comment]
Oh, I should have been clear.  I fully believe the `OperationTimeout` is in the output, but the process that _wraps_ winrm and captures it's output is truncating the logs.

We don't want any timeout on any operations, so we should change `PT60S` to `PT0S`, right?

**Comment by masterzen** [comment]
@hach-que , I'm not sure it is possible to set an 'infinite' timeout, but you can put a very large one, it's written in ISO8601 duration format: https://en.wikipedia.org/wiki/ISO_8601#Durations

Still I'd be interested in understanding why you get the error, since it should normally be caught up by winrm and simply discarded.
Are you sending `stdin` input to the commands you run?
How do you use winrm (is it the command line tool or the library, in which case if you have some code to share)?

**Comment by hach-que** [comment]
No, we're not sending anything over `stdin`.

We use it to run commands on build servers, so the commands can be hour long commands.  We notice these kinds of errors are more prominent when the machine is being thrashed by a lot of processes (CPU usage near 100%).  In these cases we expect things to be slow, but not to fail because of timeouts.

For Windows Services, giving `PT0S` as the timeout does mean infinite, so I figured it might be the same kind of thing.  Is that `PT60S` timeout applying regardless of anything else?

Right now I'm running this to try and replicate the issue, but no luck so far:

winrm ... 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -NonInteractive -InputFormat Text -OutputFormat Text -Command sleep 100000'

**Comment by masterzen** [comment]
@hach-que that's more or less how I usually test, but I wasn't able to trigger any issue (but it's on an idle VM on my laptop).
You could add some `fmt.Println` over the code in `commands.go`, `http.go` and `client.go` to see why this error bubbles up to the winrm executable.
