### ISSUE TITLE
Run integration tests in AppVeyor

### ISSUE THREAD

**Issue by StefanScherer** [masterzen/winrm#57]
I found that the Ruby WinRM gem uses AppVeyor to run real integration tests. Thanks to @mwrock there is an `appveyor.yml` that could be used to start such integration tests for this repo as well.

https://github.com/WinRb/WinRM/blob/master/appveyor.yml

Any ideas how to start with that?

**Comment by masterzen** [comment]
Thanks, that's highly interesting. 
Before investigating appveyor we need to have integration test :)
