### ISSUE TITLE
Negotiate/NTLMv2

### ISSUE THREAD

**Issue by ProTip** [masterzen/winrm#6]
I'm not sure who has the best golang winrm going now but I thought I'd throw this idea around here.  I've done near zero Cgo so I'm not sure what the barriers are, but freerdp have a pretty full on sspi implementation complete with NTLMv2(one of a kind AFIAK) and Negotiate: https://github.com/FreeRDP/FreeRDP/tree/master/winpr/libwinpr/sspi .

What would the difficulty be in utilizing this via Cgo?  This should allow win-rm negotiate auth(ntlmv2) and give us the security without the server certificates.

**Comment by paulmey** [comment]
I've just written an implementation in Go: http://github.com/paulmey/go-ntlmssp
This library does the bare minimum for auth, but I think that should be enough for most cases?

**Comment by masterzen** [comment]
@paulmey this looks interesting. I'll have a look as soon as I can find some time.

**Comment by paulmey** [comment]
Since #33 is merged now, this issue can potentially be closed... :-)
