### ISSUE TITLE
Azure remove http and tls package (build fail)

### ISSUE THREAD

**Issue by Asuan** [masterzen/winrm#60]
You are using package:
github.com/masterzen/winrm/auth.go:8:  "github.com/Azure/azure-sdk-for-go/core/http"
github.com/masterzen/winrm/auth.go:9:  "github.com/Azure/azure-sdk-for-go/core/tls"
But this package is not exists anymore.

**Comment by masterzen** [comment]
@Asuan you're right, they removed their fork now that Go 1.7 contains the correct renegociation code (see Azure/azure-sdk-for-go#375).

@hoenirvili beside moving to Go 1.7, do you see any good solutions to this problem?

**Comment by hoenirvili** [comment]
@masterzen we could vendor in the pkg,  the tls/http and move on to 1.7 when they will release it officially. Or we could just use another fork that has the patch enabled.

**Comment by masterzen** [comment]
@hoenirvili Go 1.7 is now released, hence the issue :)

Vendoring is an issue for the consumers of this library, if I'm not mistaken.
I'm more inclined to move to Go 1.7.

**Comment by gabriel-samfira** [comment]
@masterzen We have 2 choices here:

1) use version locking. We can use the latest revision of the azure SDK that still has what we need. This does not have to be a permanent thing, just long enough to allow projects still stuck on go versions < 1.7 to update their code and dependencies.

2) move to go 1.7. Given that go 1.7 is just a few days out the door, we might want to wait a bit longer, until it gets a few minor releases in.

**Comment by hoenirvili** [comment]
I'm leaning of what @gabriel-samira said. So what's your thoughts @masterzen ?

**Comment by ahmetalpbalkan** [comment]
I suggest copying deleted versions of azure/core/* packages to this repo if you don't want to move to Go 1.7 right away.

**Comment by masterzen** [comment]
This should be fixed. Please reopen if not.
