### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by strawhatboy** [masterzen/winrm#61]
It seems that there's no http proxy support for the communication, am i right?

So if I use the 'packer' (from hashicorp, which is referencing this project) behind a http proxy to create a windows EC2 images on AWS, it will hang at 'waiting for winrm'...

anyway I got the issue on my own PC which is behind the proxy, but the packer succeed to run on another AWS instance (no proxy to connect to AWS).

Thanks.

**Comment by strawhatboy** [comment]
Ah.. sry, it seems that packer is using RoundTripper which includes the proxy settings inside... not sure why it's not working on my PC...

**Comment by pearcec** [comment]
Did you ever get this working?  I couldn't.  When I ran wireshark I could see it was hitting my proxy, but trying to go direct.

**Comment by strawhatboy** [comment]
@pearcec Yes, I succeed to run packer through my proxy by modifying its source... you may like to check it here: [https://github.com/strawhatboy/packer/commit/620f107649b98105cc72141e5dffd2382a05991b](commit 620f107649b98105cc72141e5dffd2382a05991b)
