### ISSUE TITLE
Question: Kerberos support

### ISSUE THREAD

**Issue by davalente** [masterzen/winrm#72]
Any ideia when will you support kerberos?

**Comment by srinathgs** [comment]
from my understanding, kerberos will work only when you are executing from a domain machine, otherwise, Negotiate is selected. Unless this winrm library is executed from a Domain machine, you won't need kerberos.

**Comment by obeleh** [comment]
The client doesn't have to join the domain. But connecting to servers requires the client to use FQDN's

**Comment by dpotapov** [comment]
I've just published some code here https://github.com/dpotapov/winrm-auth-krb5

I've tested it only for Windows so far (it uses SSPI underneath, thus the client system must be in the domain), but should be working on Linux as well assuming `/etc/krb5.conf` is in place.

**Comment by taliesins** [comment]
Perhaps we can close this now that #123 has been implemented?

**Comment by masterzen** [comment]
Feature has been implemented, closing
