### ISSUE TITLE
Dependencies azure-sdk-for-go from auth.go no longer exist

### ISSUE THREAD

**Issue by byumov** [masterzen/winrm#84]
https://github.com/masterzen/winrm/blob/master/auth.go
```
"github.com/masterzen/azure-sdk-for-go/core/http"
"github.com/masterzen/azure-sdk-for-go/core/tls"
```
Please, fix it.

**Comment by masterzen** [comment]
I don't understand what happens, the repository is definitely here: https://github.com/masterzen/azure-sdk-for-go

**Comment by byumov** [comment]
@masterzen sorry, it's my mistake, i'll close the issue.
Thank you!
