### ISSUE TITLE
Incompatibility with  GPO settings

### ISSUE THREAD

**Issue by tmccall8829** [masterzen/winrm#87]
My organization uses Terraform for provisioning servers, which of course uses this WinRM library. We're primarily a windows company, and there are a few group policy settings -- `Allow Basic Authentication` (must be set to _Disabled_) and `Allow Unencrypted Traffic` (must be set to _Disabled_) -- that we want to have set to be in compliance with certain CIS guidelines. It's my understanding that this library is currently written to **require** the use of unencrypted traffic. Are there any efforts being made right now to make this library compatible with the above two group policy settings, i.e. work with encrypted traffic and _not_ use basic authentication? If not, we were going to take on the work ourselves. Wasn't sure if this was the right place to reach out.

**Comment by hoenirvili** [comment]
AFAIK this package supports WinRM x509 authentication and basic authentication with username:password.

**Comment by masterzen** [comment]
@tmccall8829 as @hoenirvili said, it is possible to inject a different transport than pure HTTP in the library. As such it is possible to use HTTPS (see the README or @hoenirvili example), either in encryption only or in client auth+encryption.
We also have support for NTLM, see in the README the ClientNTLM example (or PR #64).
And finally, you can also use this [Kerberos authentication](https://github.com/dpotapov/winrm-auth-krb5).

With Terraform you need to set the `https` and `use_ntlm` directive to `true` in your winrm connection. See the [terraform documentation](https://www.terraform.io/docs/provisioners/connection.html#https) for more information.

Hope this helps, feel free to reopen if needed.
Brice
