### ISSUE TITLE
Malformed XML file

### ISSUE THREAD

**Issue by mhristof** [masterzen/winrm#93]
im getting this error when trying to execute a command to a remote windows host

```
panic: Malformed XML file
```

My code is 

```go
package main

import (
	"github.com/masterzen/winrm"
	"os"
)

func main() {
	var (
		user     string = "Administrator"
		password string = "supper-awesome-password"
		host     string = "10.11.12.13"
		port     int    = 5985
	)

	endpoint := winrm.NewEndpoint(host, port, false, false, nil, nil, nil, 0)
	client, err := winrm.NewClient(endpoint, user, password)
	if err != nil {
		panic(err)
	}
	cmd := "ipconfig /all"
	_, err = client.Run(cmd, os.Stdout, os.Stderr)

	if err != nil {
		panic(err)
	}

	return
}
```

and my deps are

```
  Locking in v1.0-alpha3 (2ad3b31) for transitive dep github.com/ChrisTrenkamp/goxpath
  Locking in v0.3.0 (f21a4df) for transitive dep golang.org/x/text
  Locking in v3.2.0 (6b08a5c) for transitive dep github.com/gofrs/uuid
  Locking in master (d196dff) for transitive dep golang.org/x/net
  Using master as constraint for direct dep github.com/masterzen/winrm
  Locking in master (1d17eaf) for direct dep github.com/masterzen/winrm
  Locking in master (4572e39) for transitive dep github.com/masterzen/simplexml
  Locking in master (4a21cbd) for transitive dep github.com/Azure/go-ntlmssp
  Locking in master (a1f597e) for transitive dep golang.org/x/crypto
```

go version
```
go version go1.12.1 darwin/amd64
```

I've tried building https://github.com/masterzen/winrm-cli and running `winrm` with the same username/password/host and it was a success.

Im not sure if this is a bug or im missing something :(

**Comment by masterzen** [comment]
Hi,

Thanks for the report. I have no idea what could be wrong (except that something doesn't sent back xml). 

Since you say that the winrm-cli version is working with the same winrm server, then that means something that we introduced recently has broken something, because winrm-cli uses an older winrm (the library) version.

Would you have time to `git bisect` the problem and isolate what commit makes it not working?
On the other hand, you can also update winrm-cli dependencies to point the winrm master and check that it works or not.

I'll do my best to perform some tests this week.

Thanks!

**Comment by mhristof** [comment]
thanks for the reply, ill do the bisect and report back.

I've tried digging a bit to see if i can enable debug logs but couldnt find anything (although my golang knowledge sucks).

Is there anything i can do to get some more logs out of it ?

**Comment by mhristof** [comment]
This is starting to look like a PEBCAK :\

If i perform a `go get https://github.com/masterzen/winrm` and then use a simple script to execute a remote command, [it works](https://github.com/mhristof/winrm-example/blob/master/Dockerfile.success)

If i do a `dep init` so that golang fetches winrm and other deps and then use the script to execute a remote command, [it fails](https://github.com/mhristof/winrm-example/blob/master/Dockerfile).

I've added the dockerfiles in [this example repo](https://github.com/mhristof/winrm-example)

**Comment by mhristof** [comment]
after further searching and some external help, the issue is the version of `github.com/ChrisTrenkamp/goxpath`.

if i `dep init`, here is the list that is fetched

```
# dep status
PROJECT                           CONSTRAINT     VERSION        REVISION  LATEST       PKGS USED
github.com/Azure/go-ntlmssp       branch master  branch master  4a21cbd   4a21cbd      1
github.com/ChrisTrenkamp/goxpath  v1.0-alpha3    v1.0-alpha3    2ad3b31   v1.0-alpha3  14
github.com/gofrs/uuid             v3.2.0         v3.2.0         6b08a5c   v3.2.0       1
github.com/masterzen/simplexml    branch master  branch master  4572e39   4572e39      1
github.com/masterzen/winrm        branch master  branch master  1d17eaf   1d17eaf      2
golang.org/x/crypto               branch master  branch master  a1f597e   a1f597e      1
golang.org/x/net                  branch master  branch master  1272bf9   1272bf9      3
golang.org/x/text                 v0.3.0         v0.3.0         f21a4df   v0.3.0       17
```

and that causes the xml error.

But if i add a constrain to fetch the master branch in `Gopkg.toml`

```
[[override]]
  name = "github.com/ChrisTrenkamp/goxpath"
  branch = "master"
```

and `dep ensure`, i get this list

```
# dep status
PROJECT                           CONSTRAINT                VERSION        REVISION  LATEST   PKGS USED
github.com/Azure/go-ntlmssp       branch master             branch master  4a21cbd   4a21cbd  1
github.com/ChrisTrenkamp/goxpath  branch master (override)  branch master  c385f95   c385f95  14
github.com/gofrs/uuid             v3.2.0                    v3.2.0         6b08a5c   v3.2.0   1
github.com/masterzen/simplexml    branch master             branch master  4572e39   4572e39  1
github.com/masterzen/winrm        branch master             branch master  1d17eaf   1d17eaf  2
golang.org/x/crypto               branch master             branch master  a1f597e   a1f597e  1
golang.org/x/net                  branch master             branch master  1272bf9   1272bf9  3
golang.org/x/text                 v0.3.0                    v0.3.0         f21a4df   v0.3.0   17
```

which makes my test program to work without the xml error.

**Comment by masterzen** [comment]
Many thanks for the troubleshooting!
You did an awesome job :)

I'll fix that bad dependency tomorrow.

**Comment by masterzen** [comment]
Hi @mhristof ,

Indeed, `dep` always favor a tag as explained in the [documentation](https://golang.github.io/dep/docs/migrating.html):

> dep generally prefers semantic versioning-tagged releases to branches (when not given any additional rules). This is a significant shift from the "default branch" model of go get and some other tools. It can result in dep making surprising choices for dependencies for which it could not infer a rule.

You won't get the issue if you use Go 1.11 module system, because the provided `go.mod` points to a working version of https://github.com/ChrisTrenkamp/goxpath.

Since we can't support every go vendor system (and it would be hard to sync them all), we're using the go module system.

Thank you for doing all the hard work troubleshooting this issue.

I'm going to close this ticket, feel free to reopen if you think there's something we should do in this project to solve the issue.

**Comment by mhristof** [comment]
makes sense, i need to switch to `go.mod` anyway.

Cheers for the help
