### ISSUE TITLE
/bin/sh: 3: godep: not found

### ISSUE THREAD

**Issue by Langriklol** [masterzen/winrm#94]
Hi, make command gives me error of unsuccessful dependency (godep), but I have godep installed. How do I fix this error?
```
root@kali:/root/go-workspace/winrm-cli$ make
==> Installing dependencies
==> Installing godep and restoring dependencies
/bin/sh: 3: godep: not found
make: *** [Makefile:20: deps] Error 127

```

**Comment by masterzen** [comment]
This project is using go mod now, so I think this issue has been fixed.
